List<String> governorateList = [
  'Alexandria',
  'Aswan',
  'Asyut',
  'Beheira',
  'Beni Suef',
  'Cairo',
  'Dakahlia',
  'Damietta',
  'Faiyum',
  'Gharbia',
  'Giza',
  'Ismailia',
  'Kafr El Sheikh',
  'Luxor',
  'Matruh',
  'Minya',
  'Monufia',
  'New Valley',
  'North Sinai',
  'Port Said',
  'Qalyubia',
  'Qena',
  'Red Sea',
  'Sharqia',
  'Sohag',
  'South',
  'Suez',
];
List<String> listSpecialty = [
  'Infectious Disease Physician',
  'Internal Medicine Physician',
  'Obstetrician/Gynecologist',
  'Physician Executive',
  'Gastroenterologist',
  'Otolaryngologist',
  'Anesthesiologist',
  'Family Physician',
  'Endocrinologist',
  'Ophthalmologist',
  'Dermatologist',
  'Pulmonologist',
  'Nephrologist',
  'Pediatrician',
  'Psychiatrist',
  'Cardiologist',
  'Neurologist',
  'Radiologist',
  'Oncologist',
  'Surgeon',
//   '',
//   '',
//   '',
//   '',
//   '','',
//   '',
//   '','','','','',
];

List<String> materialStatus = [
  'Single',
  'Married',
  'Divorced',
  'Separated',
  'Widowed',
];
List<String> workingDays = [
  'Saturday',
  'Sunday',
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
];